### PR TITLE
Multiloader support 1.19.2 | Fabric & Forge

### PR DESCRIPTION
**Pull request by AndreAugustoDev**

### CODE REVIEW

**Comment by XxRexRaptorxX** [comment]
Thanks for your awesome work!:)

**Comment by XxRexRaptorxX** [comment]
Sorry but this is my first multiloader setup and & I'm not that experienced. I get this error after i exported the mod for fabric:

```
java.lang.AbstractMethodError: Receiver class xxrexraptorxx.lexicon.main.fabric.event.ModEventsFabric$GiveBookOnFirstJoin does not define or inherit an implementation of the resolved method 'abstract void onPlayReady(net.minecraft.class_3244, net.fabricmc.fabric.api.networking.v1.PacketSender, net.minecraft.server.MinecraftServer)' of interface net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents$Join.
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48)
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65)
	at net.minecraft.class_3324.handler$zen000$handlePlayerConnection(class_3324.java:2513)
	at net.minecraft.class_3324.method_14570(class_3324.java:200)
	at net.minecraft.class_3248.method_33800(class_3248.java:151)
	at net.minecraft.class_3248.method_14384(class_3248.java:138)
	at net.minecraft.class_3248.redirect$zeo000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18784(class_3248.java:73)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Do you know what's wrong?

**Comment by AndreAugustoDev** [comment]
It seems to me that the required Fabric API class could not be found
If this happened in development, run the main clean task and reopen the project, it could be that the dependencies were not imported correctly.
If starting normally from the launcher, try updating the Fabric API to version 0.14.18

**Comment by XxRexRaptorxX** [comment]
That only happens if i want to run the exported mod

**Pull request merged**
