### PR TITLE
 Translation request

### PR DESCRIPTION
**Pull request by pandim**

### CODE REVIEW

**Review by XxRexRaptorxX — APPROVED** [review]
Thanks for your translation, I'll check it again and then add it to the new version

**Comment by pandim** [comment]
:)
My English is very bad. I translated Google Translator and there may be errors, sorry :(
The translation was necessary for my child.

**Comment by XxRexRaptorxX** [comment]
Did you check the formatting ingame? it may be that lines have shifted or that prefixes have been accidentally changed

**Comment by XxRexRaptorxX** [comment]
i don't know why, but the pages does not appear as translated if i change the language to ru/ru

**Comment by pandim** [comment]
Good afternoon! If you play in English and switch the interface in the game, the language does not change.
You need to go to the main menu and change the language there! Helped me :)

**Comment by pandim** [comment]
https://github.com/VazkiiMods/Patchouli/issues/494

**Comment by pandim** [comment]
> Did you check the formatting ingame? it may be that lines have shifted or that prefixes have been accidentally changed

Partially I checked, gradually correct and update

**Comment by XxRexRaptorxX** [comment]
Ahhh i didn't know that. Thanks.

Translators get their own rank in my discord, so check it out if you're interested :D https://discord.gg/ycRJJk8EXV

**Comment by XxRexRaptorxX** [comment]
https://www.curseforge.com/minecraft/mc-mods/lexicon/files/3833390

**Pull request merged**
